using System.Windows.Forms;
using System.Drawing;

namespace BoomSQL
{
    partial class Form1
    {
        /// <summary>
        /// Required designer variable.
        /// </summary>
        private System.ComponentModel.IContainer components = null;

        // Add this panel for page content
        private Panel contentPanel;

        /// <summary>
        /// Clean up any resources being used.
        /// </summary>
        /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        /// <summary>
        /// Required method for Designer support - do not modify
        /// the contents of this method with the code editor.
        /// </summary>
        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(Form1));
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges1 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges2 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges3 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges4 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges5 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges6 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges borderEdges7 = new Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges1 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges2 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges3 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges4 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            bunifuGradientPanel1 = new Bunifu.UI.WinForms.BunifuGradientPanel();
            aboutbutton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            label2 = new Label();
            exitbutton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            settingsbutton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            dumperbutton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            Testerbutton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            crawlerbutton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            Dorkbutton = new Bunifu.UI.WinForms.BunifuButton.BunifuButton();
            guna2ControlBox1 = new Guna.UI2.WinForms.Guna2ControlBox();
            guna2ControlBox2 = new Guna.UI2.WinForms.Guna2ControlBox();
            guna2ResizeForm1 = new Guna.UI2.WinForms.Guna2ResizeForm(components);
            contentPanel = new Panel();
            bunifuGradientPanel1.SuspendLayout();
            SuspendLayout();
            // 
            // bunifuGradientPanel1
            // 
            bunifuGradientPanel1.BackColor = Color.Transparent;
            bunifuGradientPanel1.BackgroundImage = (Image)resources.GetObject("bunifuGradientPanel1.BackgroundImage");
            bunifuGradientPanel1.BackgroundImageLayout = ImageLayout.Stretch;
            bunifuGradientPanel1.BorderRadius = 1;
            bunifuGradientPanel1.Controls.Add(aboutbutton);
            bunifuGradientPanel1.Controls.Add(label2);
            bunifuGradientPanel1.Controls.Add(exitbutton);
            bunifuGradientPanel1.Controls.Add(settingsbutton);
            bunifuGradientPanel1.Controls.Add(dumperbutton);
            bunifuGradientPanel1.Controls.Add(Testerbutton);
            bunifuGradientPanel1.Controls.Add(crawlerbutton);
            bunifuGradientPanel1.Controls.Add(Dorkbutton);
            bunifuGradientPanel1.Dock = DockStyle.Left;
            bunifuGradientPanel1.GradientBottomLeft = Color.Red;
            bunifuGradientPanel1.GradientBottomRight = Color.Black;
            bunifuGradientPanel1.GradientTopLeft = Color.Red;
            bunifuGradientPanel1.GradientTopRight = Color.Black;
            bunifuGradientPanel1.Location = new Point(0, 0);
            bunifuGradientPanel1.Name = "bunifuGradientPanel1";
            bunifuGradientPanel1.Quality = 10;
            bunifuGradientPanel1.Size = new Size(469, 1381);
            bunifuGradientPanel1.TabIndex = 0;
            // 
            // aboutbutton
            // 
            aboutbutton.AllowAnimations = true;
            aboutbutton.AllowMouseEffects = true;
            aboutbutton.AllowToggling = false;
            aboutbutton.AnimationSpeed = 200;
            aboutbutton.AutoGenerateColors = false;
            aboutbutton.AutoRoundBorders = false;
            aboutbutton.AutoSizeLeftIcon = true;
            aboutbutton.AutoSizeRightIcon = true;
            aboutbutton.BackColor = Color.Transparent;
            aboutbutton.BackColor1 = Color.FromArgb(51, 122, 183);
            aboutbutton.BackgroundImage = (Image)resources.GetObject("aboutbutton.BackgroundImage");
            aboutbutton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            aboutbutton.ButtonText = "About";
            aboutbutton.ButtonTextMarginLeft = 0;
            aboutbutton.ColorContrastOnClick = 45;
            aboutbutton.ColorContrastOnHover = 45;
            borderEdges1.BottomLeft = true;
            borderEdges1.BottomRight = true;
            borderEdges1.TopLeft = true;
            borderEdges1.TopRight = true;
            aboutbutton.CustomizableEdges = borderEdges1;
            aboutbutton.DialogResult = DialogResult.None;
            aboutbutton.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            aboutbutton.DisabledFillColor = Color.Empty;
            aboutbutton.DisabledForecolor = Color.Empty;
            aboutbutton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            aboutbutton.Font = new Font("Showcard Gothic", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            aboutbutton.ForeColor = Color.White;
            aboutbutton.IconLeft = (Image)resources.GetObject("aboutbutton.IconLeft");
            aboutbutton.IconLeftAlign = ContentAlignment.MiddleLeft;
            aboutbutton.IconLeftCursor = Cursors.Default;
            aboutbutton.IconLeftPadding = new Padding(11, 3, 3, 3);
            aboutbutton.IconMarginLeft = 11;
            aboutbutton.IconPadding = 10;
            aboutbutton.IconRight = null;
            aboutbutton.IconRightAlign = ContentAlignment.MiddleRight;
            aboutbutton.IconRightCursor = Cursors.Default;
            aboutbutton.IconRightPadding = new Padding(3, 3, 7, 3);
            aboutbutton.IconSize = 25;
            aboutbutton.IdleBorderColor = Color.Empty;
            aboutbutton.IdleBorderRadius = 0;
            aboutbutton.IdleBorderThickness = 0;
            aboutbutton.IdleFillColor = Color.Empty;
            aboutbutton.IdleIconLeftImage = (Image)resources.GetObject("aboutbutton.IdleIconLeftImage");
            aboutbutton.IdleIconRightImage = null;
            aboutbutton.IndicateFocus = false;
            aboutbutton.Location = new Point(0, 980);
            aboutbutton.Name = "aboutbutton";
            aboutbutton.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            aboutbutton.OnDisabledState.BorderRadius = 1;
            aboutbutton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            aboutbutton.OnDisabledState.BorderThickness = 1;
            aboutbutton.OnDisabledState.FillColor = Color.Transparent;
            aboutbutton.OnDisabledState.ForeColor = Color.Transparent;
            aboutbutton.OnDisabledState.IconLeftImage = null;
            aboutbutton.OnDisabledState.IconRightImage = null;
            aboutbutton.onHoverState.BorderColor = Color.Transparent;
            aboutbutton.onHoverState.BorderRadius = 1;
            aboutbutton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            aboutbutton.onHoverState.BorderThickness = 1;
            aboutbutton.onHoverState.FillColor = Color.Transparent;
            aboutbutton.onHoverState.ForeColor = Color.White;
            aboutbutton.onHoverState.IconLeftImage = null;
            aboutbutton.onHoverState.IconRightImage = null;
            aboutbutton.OnIdleState.BorderColor = Color.Transparent;
            aboutbutton.OnIdleState.BorderRadius = 1;
            aboutbutton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            aboutbutton.OnIdleState.BorderThickness = 1;
            aboutbutton.OnIdleState.FillColor = Color.Transparent;
            aboutbutton.OnIdleState.ForeColor = Color.White;
            aboutbutton.OnIdleState.IconLeftImage = (Image)resources.GetObject("aboutbutton.OnIdleState.IconLeftImage");
            aboutbutton.OnIdleState.IconRightImage = null;
            aboutbutton.OnPressedState.BorderColor = Color.Transparent;
            aboutbutton.OnPressedState.BorderRadius = 1;
            aboutbutton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            aboutbutton.OnPressedState.BorderThickness = 1;
            aboutbutton.OnPressedState.FillColor = Color.Transparent;
            aboutbutton.OnPressedState.ForeColor = Color.White;
            aboutbutton.OnPressedState.IconLeftImage = null;
            aboutbutton.OnPressedState.IconRightImage = null;
            aboutbutton.Size = new Size(469, 112);
            aboutbutton.TabIndex = 6;
            aboutbutton.TextAlign = ContentAlignment.MiddleCenter;
            aboutbutton.TextAlignment = HorizontalAlignment.Center;
            aboutbutton.TextMarginLeft = 0;
            aboutbutton.TextPadding = new Padding(0);
            aboutbutton.UseDefaultRadiusAndThickness = true;
            // 
            // label2
            // 
            label2.AutoSize = true;
            label2.Font = new Font("Matura MT Script Capitals", 16.125F, FontStyle.Bold, GraphicsUnit.Point, 0);
            label2.ForeColor = Color.Aqua;
            label2.ImageAlign = ContentAlignment.TopLeft;
            label2.Location = new Point(5, 6);
            label2.Name = "label2";
            label2.Size = new Size(226, 57);
            label2.TabIndex = 4;
            label2.Text = "SqlBoom";
            label2.Click += label2_Click;
            // 
            // exitbutton
            // 
            exitbutton.AllowAnimations = true;
            exitbutton.AllowMouseEffects = true;
            exitbutton.AllowToggling = false;
            exitbutton.AnimationSpeed = 200;
            exitbutton.AutoGenerateColors = false;
            exitbutton.AutoRoundBorders = false;
            exitbutton.AutoSizeLeftIcon = true;
            exitbutton.AutoSizeRightIcon = true;
            exitbutton.BackColor = Color.Transparent;
            exitbutton.BackColor1 = Color.FromArgb(51, 122, 183);
            exitbutton.BackgroundImage = (Image)resources.GetObject("exitbutton.BackgroundImage");
            exitbutton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            exitbutton.ButtonText = "Exit";
            exitbutton.ButtonTextMarginLeft = 0;
            exitbutton.ColorContrastOnClick = 45;
            exitbutton.ColorContrastOnHover = 45;
            borderEdges2.BottomLeft = true;
            borderEdges2.BottomRight = true;
            borderEdges2.TopLeft = true;
            borderEdges2.TopRight = true;
            exitbutton.CustomizableEdges = borderEdges2;
            exitbutton.DialogResult = DialogResult.None;
            exitbutton.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            exitbutton.DisabledFillColor = Color.Empty;
            exitbutton.DisabledForecolor = Color.Empty;
            exitbutton.Dock = DockStyle.Bottom;
            exitbutton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            exitbutton.Font = new Font("Showcard Gothic", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            exitbutton.ForeColor = Color.White;
            exitbutton.IconLeft = (Image)resources.GetObject("exitbutton.IconLeft");
            exitbutton.IconLeftAlign = ContentAlignment.MiddleLeft;
            exitbutton.IconLeftCursor = Cursors.Default;
            exitbutton.IconLeftPadding = new Padding(11, 3, 3, 3);
            exitbutton.IconMarginLeft = 11;
            exitbutton.IconPadding = 10;
            exitbutton.IconRight = null;
            exitbutton.IconRightAlign = ContentAlignment.MiddleRight;
            exitbutton.IconRightCursor = Cursors.Default;
            exitbutton.IconRightPadding = new Padding(3, 3, 7, 3);
            exitbutton.IconSize = 25;
            exitbutton.IdleBorderColor = Color.Empty;
            exitbutton.IdleBorderRadius = 0;
            exitbutton.IdleBorderThickness = 0;
            exitbutton.IdleFillColor = Color.Empty;
            exitbutton.IdleIconLeftImage = (Image)resources.GetObject("exitbutton.IdleIconLeftImage");
            exitbutton.IdleIconRightImage = null;
            exitbutton.IndicateFocus = false;
            exitbutton.Location = new Point(0, 1269);
            exitbutton.Name = "exitbutton";
            exitbutton.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            exitbutton.OnDisabledState.BorderRadius = 1;
            exitbutton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            exitbutton.OnDisabledState.BorderThickness = 1;
            exitbutton.OnDisabledState.FillColor = Color.Transparent;
            exitbutton.OnDisabledState.ForeColor = Color.Transparent;
            exitbutton.OnDisabledState.IconLeftImage = null;
            exitbutton.OnDisabledState.IconRightImage = null;
            exitbutton.onHoverState.BorderColor = Color.FromArgb(192, 0, 0);
            exitbutton.onHoverState.BorderRadius = 1;
            exitbutton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            exitbutton.onHoverState.BorderThickness = 1;
            exitbutton.onHoverState.FillColor = Color.FromArgb(192, 0, 0);
            exitbutton.onHoverState.ForeColor = Color.White;
            exitbutton.onHoverState.IconLeftImage = null;
            exitbutton.onHoverState.IconRightImage = null;
            exitbutton.OnIdleState.BorderColor = Color.Transparent;
            exitbutton.OnIdleState.BorderRadius = 1;
            exitbutton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            exitbutton.OnIdleState.BorderThickness = 1;
            exitbutton.OnIdleState.FillColor = Color.Transparent;
            exitbutton.OnIdleState.ForeColor = Color.White;
            exitbutton.OnIdleState.IconLeftImage = (Image)resources.GetObject("exitbutton.OnIdleState.IconLeftImage");
            exitbutton.OnIdleState.IconRightImage = null;
            exitbutton.OnPressedState.BorderColor = Color.FromArgb(40, 96, 144);
            exitbutton.OnPressedState.BorderRadius = 1;
            exitbutton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            exitbutton.OnPressedState.BorderThickness = 1;
            exitbutton.OnPressedState.FillColor = Color.FromArgb(40, 96, 144);
            exitbutton.OnPressedState.ForeColor = Color.White;
            exitbutton.OnPressedState.IconLeftImage = null;
            exitbutton.OnPressedState.IconRightImage = null;
            exitbutton.Size = new Size(469, 112);
            exitbutton.TabIndex = 5;
            exitbutton.TextAlign = ContentAlignment.MiddleCenter;
            exitbutton.TextAlignment = HorizontalAlignment.Center;
            exitbutton.TextMarginLeft = 0;
            exitbutton.TextPadding = new Padding(0);
            exitbutton.UseDefaultRadiusAndThickness = true;
            exitbutton.Click += exitbutton_Click;
            // 
            // settingsbutton
            // 
            settingsbutton.AllowAnimations = true;
            settingsbutton.AllowMouseEffects = true;
            settingsbutton.AllowToggling = false;
            settingsbutton.AnimationSpeed = 200;
            settingsbutton.AutoGenerateColors = false;
            settingsbutton.AutoRoundBorders = false;
            settingsbutton.AutoSizeLeftIcon = true;
            settingsbutton.AutoSizeRightIcon = true;
            settingsbutton.BackColor = Color.Transparent;
            settingsbutton.BackColor1 = Color.FromArgb(51, 122, 183);
            settingsbutton.BackgroundImage = (Image)resources.GetObject("settingsbutton.BackgroundImage");
            settingsbutton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            settingsbutton.ButtonText = "Settings";
            settingsbutton.ButtonTextMarginLeft = 0;
            settingsbutton.ColorContrastOnClick = 45;
            settingsbutton.ColorContrastOnHover = 45;
            borderEdges3.BottomLeft = true;
            borderEdges3.BottomRight = true;
            borderEdges3.TopLeft = true;
            borderEdges3.TopRight = true;
            settingsbutton.CustomizableEdges = borderEdges3;
            settingsbutton.DialogResult = DialogResult.None;
            settingsbutton.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            settingsbutton.DisabledFillColor = Color.Empty;
            settingsbutton.DisabledForecolor = Color.Empty;
            settingsbutton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            settingsbutton.Font = new Font("Showcard Gothic", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            settingsbutton.ForeColor = Color.White;
            settingsbutton.IconLeft = (Image)resources.GetObject("settingsbutton.IconLeft");
            settingsbutton.IconLeftAlign = ContentAlignment.MiddleLeft;
            settingsbutton.IconLeftCursor = Cursors.Default;
            settingsbutton.IconLeftPadding = new Padding(11, 3, 3, 3);
            settingsbutton.IconMarginLeft = 11;
            settingsbutton.IconPadding = 10;
            settingsbutton.IconRight = null;
            settingsbutton.IconRightAlign = ContentAlignment.MiddleRight;
            settingsbutton.IconRightCursor = Cursors.Default;
            settingsbutton.IconRightPadding = new Padding(3, 3, 7, 3);
            settingsbutton.IconSize = 25;
            settingsbutton.IdleBorderColor = Color.Empty;
            settingsbutton.IdleBorderRadius = 0;
            settingsbutton.IdleBorderThickness = 0;
            settingsbutton.IdleFillColor = Color.Empty;
            settingsbutton.IdleIconLeftImage = (Image)resources.GetObject("settingsbutton.IdleIconLeftImage");
            settingsbutton.IdleIconRightImage = null;
            settingsbutton.IndicateFocus = false;
            settingsbutton.Location = new Point(-3, 816);
            settingsbutton.Name = "settingsbutton";
            settingsbutton.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            settingsbutton.OnDisabledState.BorderRadius = 1;
            settingsbutton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            settingsbutton.OnDisabledState.BorderThickness = 1;
            settingsbutton.OnDisabledState.FillColor = Color.Transparent;
            settingsbutton.OnDisabledState.ForeColor = Color.Transparent;
            settingsbutton.OnDisabledState.IconLeftImage = null;
            settingsbutton.OnDisabledState.IconRightImage = null;
            settingsbutton.onHoverState.BorderColor = Color.Transparent;
            settingsbutton.onHoverState.BorderRadius = 1;
            settingsbutton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            settingsbutton.onHoverState.BorderThickness = 1;
            settingsbutton.onHoverState.FillColor = Color.Transparent;
            settingsbutton.onHoverState.ForeColor = Color.White;
            settingsbutton.onHoverState.IconLeftImage = null;
            settingsbutton.onHoverState.IconRightImage = null;
            settingsbutton.OnIdleState.BorderColor = Color.Transparent;
            settingsbutton.OnIdleState.BorderRadius = 1;
            settingsbutton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            settingsbutton.OnIdleState.BorderThickness = 1;
            settingsbutton.OnIdleState.FillColor = Color.Transparent;
            settingsbutton.OnIdleState.ForeColor = Color.White;
            settingsbutton.OnIdleState.IconLeftImage = (Image)resources.GetObject("settingsbutton.OnIdleState.IconLeftImage");
            settingsbutton.OnIdleState.IconRightImage = null;
            settingsbutton.OnPressedState.BorderColor = Color.Transparent;
            settingsbutton.OnPressedState.BorderRadius = 1;
            settingsbutton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            settingsbutton.OnPressedState.BorderThickness = 1;
            settingsbutton.OnPressedState.FillColor = Color.Transparent;
            settingsbutton.OnPressedState.ForeColor = Color.White;
            settingsbutton.OnPressedState.IconLeftImage = null;
            settingsbutton.OnPressedState.IconRightImage = null;
            settingsbutton.Size = new Size(469, 112);
            settingsbutton.TabIndex = 4;
            settingsbutton.TextAlign = ContentAlignment.MiddleCenter;
            settingsbutton.TextAlignment = HorizontalAlignment.Center;
            settingsbutton.TextMarginLeft = 0;
            settingsbutton.TextPadding = new Padding(0);
            settingsbutton.UseDefaultRadiusAndThickness = true;
            // 
            // dumperbutton
            // 
            dumperbutton.AllowAnimations = true;
            dumperbutton.AllowMouseEffects = true;
            dumperbutton.AllowToggling = false;
            dumperbutton.AnimationSpeed = 200;
            dumperbutton.AutoGenerateColors = false;
            dumperbutton.AutoRoundBorders = false;
            dumperbutton.AutoSizeLeftIcon = true;
            dumperbutton.AutoSizeRightIcon = true;
            dumperbutton.BackColor = Color.Transparent;
            dumperbutton.BackColor1 = Color.FromArgb(51, 122, 183);
            dumperbutton.BackgroundImage = (Image)resources.GetObject("dumperbutton.BackgroundImage");
            dumperbutton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            dumperbutton.ButtonText = "Dumper";
            dumperbutton.ButtonTextMarginLeft = 0;
            dumperbutton.ColorContrastOnClick = 45;
            dumperbutton.ColorContrastOnHover = 45;
            borderEdges4.BottomLeft = true;
            borderEdges4.BottomRight = true;
            borderEdges4.TopLeft = true;
            borderEdges4.TopRight = true;
            dumperbutton.CustomizableEdges = borderEdges4;
            dumperbutton.DialogResult = DialogResult.None;
            dumperbutton.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            dumperbutton.DisabledFillColor = Color.Empty;
            dumperbutton.DisabledForecolor = Color.Empty;
            dumperbutton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            dumperbutton.Font = new Font("Showcard Gothic", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            dumperbutton.ForeColor = Color.White;
            dumperbutton.IconLeft = (Image)resources.GetObject("dumperbutton.IconLeft");
            dumperbutton.IconLeftAlign = ContentAlignment.MiddleLeft;
            dumperbutton.IconLeftCursor = Cursors.Default;
            dumperbutton.IconLeftPadding = new Padding(11, 3, 3, 3);
            dumperbutton.IconMarginLeft = 11;
            dumperbutton.IconPadding = 10;
            dumperbutton.IconRight = null;
            dumperbutton.IconRightAlign = ContentAlignment.MiddleRight;
            dumperbutton.IconRightCursor = Cursors.Default;
            dumperbutton.IconRightPadding = new Padding(3, 3, 7, 3);
            dumperbutton.IconSize = 25;
            dumperbutton.IdleBorderColor = Color.Empty;
            dumperbutton.IdleBorderRadius = 0;
            dumperbutton.IdleBorderThickness = 0;
            dumperbutton.IdleFillColor = Color.Empty;
            dumperbutton.IdleIconLeftImage = (Image)resources.GetObject("dumperbutton.IdleIconLeftImage");
            dumperbutton.IdleIconRightImage = null;
            dumperbutton.IndicateFocus = false;
            dumperbutton.Location = new Point(0, 668);
            dumperbutton.Name = "dumperbutton";
            dumperbutton.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            dumperbutton.OnDisabledState.BorderRadius = 1;
            dumperbutton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            dumperbutton.OnDisabledState.BorderThickness = 1;
            dumperbutton.OnDisabledState.FillColor = Color.Transparent;
            dumperbutton.OnDisabledState.ForeColor = Color.Transparent;
            dumperbutton.OnDisabledState.IconLeftImage = null;
            dumperbutton.OnDisabledState.IconRightImage = null;
            dumperbutton.onHoverState.BorderColor = Color.Transparent;
            dumperbutton.onHoverState.BorderRadius = 1;
            dumperbutton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            dumperbutton.onHoverState.BorderThickness = 1;
            dumperbutton.onHoverState.FillColor = Color.Transparent;
            dumperbutton.onHoverState.ForeColor = Color.White;
            dumperbutton.onHoverState.IconLeftImage = null;
            dumperbutton.onHoverState.IconRightImage = null;
            dumperbutton.OnIdleState.BorderColor = Color.Transparent;
            dumperbutton.OnIdleState.BorderRadius = 1;
            dumperbutton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            dumperbutton.OnIdleState.BorderThickness = 1;
            dumperbutton.OnIdleState.FillColor = Color.Transparent;
            dumperbutton.OnIdleState.ForeColor = Color.White;
            dumperbutton.OnIdleState.IconLeftImage = (Image)resources.GetObject("dumperbutton.OnIdleState.IconLeftImage");
            dumperbutton.OnIdleState.IconRightImage = null;
            dumperbutton.OnPressedState.BorderColor = Color.Transparent;
            dumperbutton.OnPressedState.BorderRadius = 1;
            dumperbutton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            dumperbutton.OnPressedState.BorderThickness = 1;
            dumperbutton.OnPressedState.FillColor = Color.Transparent;
            dumperbutton.OnPressedState.ForeColor = Color.White;
            dumperbutton.OnPressedState.IconLeftImage = null;
            dumperbutton.OnPressedState.IconRightImage = null;
            dumperbutton.Size = new Size(469, 112);
            dumperbutton.TabIndex = 3;
            dumperbutton.TextAlign = ContentAlignment.MiddleCenter;
            dumperbutton.TextAlignment = HorizontalAlignment.Center;
            dumperbutton.TextMarginLeft = 0;
            dumperbutton.TextPadding = new Padding(0);
            dumperbutton.UseDefaultRadiusAndThickness = true;
            // 
            // Testerbutton
            // 
            Testerbutton.AllowAnimations = true;
            Testerbutton.AllowMouseEffects = true;
            Testerbutton.AllowToggling = false;
            Testerbutton.AnimationSpeed = 200;
            Testerbutton.AutoGenerateColors = false;
            Testerbutton.AutoRoundBorders = false;
            Testerbutton.AutoSizeLeftIcon = true;
            Testerbutton.AutoSizeRightIcon = true;
            Testerbutton.BackColor = Color.Transparent;
            Testerbutton.BackColor1 = Color.FromArgb(51, 122, 183);
            Testerbutton.BackgroundImage = (Image)resources.GetObject("Testerbutton.BackgroundImage");
            Testerbutton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Testerbutton.ButtonText = "Tester";
            Testerbutton.ButtonTextMarginLeft = 0;
            Testerbutton.ColorContrastOnClick = 45;
            Testerbutton.ColorContrastOnHover = 45;
            borderEdges5.BottomLeft = true;
            borderEdges5.BottomRight = true;
            borderEdges5.TopLeft = true;
            borderEdges5.TopRight = true;
            Testerbutton.CustomizableEdges = borderEdges5;
            Testerbutton.DialogResult = DialogResult.None;
            Testerbutton.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            Testerbutton.DisabledFillColor = Color.Empty;
            Testerbutton.DisabledForecolor = Color.Empty;
            Testerbutton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            Testerbutton.Font = new Font("Showcard Gothic", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            Testerbutton.ForeColor = Color.White;
            Testerbutton.IconLeft = (Image)resources.GetObject("Testerbutton.IconLeft");
            Testerbutton.IconLeftAlign = ContentAlignment.MiddleLeft;
            Testerbutton.IconLeftCursor = Cursors.Default;
            Testerbutton.IconLeftPadding = new Padding(11, 3, 3, 3);
            Testerbutton.IconMarginLeft = 11;
            Testerbutton.IconPadding = 10;
            Testerbutton.IconRight = null;
            Testerbutton.IconRightAlign = ContentAlignment.MiddleRight;
            Testerbutton.IconRightCursor = Cursors.Default;
            Testerbutton.IconRightPadding = new Padding(3, 3, 7, 3);
            Testerbutton.IconSize = 25;
            Testerbutton.IdleBorderColor = Color.Empty;
            Testerbutton.IdleBorderRadius = 0;
            Testerbutton.IdleBorderThickness = 0;
            Testerbutton.IdleFillColor = Color.Empty;
            Testerbutton.IdleIconLeftImage = (Image)resources.GetObject("Testerbutton.IdleIconLeftImage");
            Testerbutton.IdleIconRightImage = null;
            Testerbutton.IndicateFocus = false;
            Testerbutton.Location = new Point(-3, 526);
            Testerbutton.Name = "Testerbutton";
            Testerbutton.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            Testerbutton.OnDisabledState.BorderRadius = 1;
            Testerbutton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Testerbutton.OnDisabledState.BorderThickness = 1;
            Testerbutton.OnDisabledState.FillColor = Color.Transparent;
            Testerbutton.OnDisabledState.ForeColor = Color.Transparent;
            Testerbutton.OnDisabledState.IconLeftImage = null;
            Testerbutton.OnDisabledState.IconRightImage = null;
            Testerbutton.onHoverState.BorderColor = Color.Transparent;
            Testerbutton.onHoverState.BorderRadius = 1;
            Testerbutton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Testerbutton.onHoverState.BorderThickness = 1;
            Testerbutton.onHoverState.FillColor = Color.Transparent;
            Testerbutton.onHoverState.ForeColor = Color.Transparent;
            Testerbutton.onHoverState.IconLeftImage = null;
            Testerbutton.onHoverState.IconRightImage = null;
            Testerbutton.OnIdleState.BorderColor = Color.Transparent;
            Testerbutton.OnIdleState.BorderRadius = 1;
            Testerbutton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Testerbutton.OnIdleState.BorderThickness = 1;
            Testerbutton.OnIdleState.FillColor = Color.Transparent;
            Testerbutton.OnIdleState.ForeColor = Color.White;
            Testerbutton.OnIdleState.IconLeftImage = (Image)resources.GetObject("Testerbutton.OnIdleState.IconLeftImage");
            Testerbutton.OnIdleState.IconRightImage = null;
            Testerbutton.OnPressedState.BorderColor = Color.Transparent;
            Testerbutton.OnPressedState.BorderRadius = 1;
            Testerbutton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Testerbutton.OnPressedState.BorderThickness = 1;
            Testerbutton.OnPressedState.FillColor = Color.Transparent;
            Testerbutton.OnPressedState.ForeColor = Color.White;
            Testerbutton.OnPressedState.IconLeftImage = null;
            Testerbutton.OnPressedState.IconRightImage = null;
            Testerbutton.Size = new Size(469, 112);
            Testerbutton.TabIndex = 2;
            Testerbutton.TextAlign = ContentAlignment.MiddleCenter;
            Testerbutton.TextAlignment = HorizontalAlignment.Center;
            Testerbutton.TextMarginLeft = 0;
            Testerbutton.TextPadding = new Padding(0);
            Testerbutton.UseDefaultRadiusAndThickness = true;
            // 
            // crawlerbutton
            // 
            crawlerbutton.AllowAnimations = true;
            crawlerbutton.AllowMouseEffects = true;
            crawlerbutton.AllowToggling = false;
            crawlerbutton.AnimationSpeed = 200;
            crawlerbutton.AutoGenerateColors = false;
            crawlerbutton.AutoRoundBorders = false;
            crawlerbutton.AutoSizeLeftIcon = true;
            crawlerbutton.AutoSizeRightIcon = true;
            crawlerbutton.BackColor = Color.Transparent;
            crawlerbutton.BackColor1 = Color.FromArgb(51, 122, 183);
            crawlerbutton.BackgroundImage = (Image)resources.GetObject("crawlerbutton.BackgroundImage");
            crawlerbutton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            crawlerbutton.ButtonText = "Crawler";
            crawlerbutton.ButtonTextMarginLeft = 0;
            crawlerbutton.ColorContrastOnClick = 45;
            crawlerbutton.ColorContrastOnHover = 45;
            borderEdges6.BottomLeft = true;
            borderEdges6.BottomRight = true;
            borderEdges6.TopLeft = true;
            borderEdges6.TopRight = true;
            crawlerbutton.CustomizableEdges = borderEdges6;
            crawlerbutton.DialogResult = DialogResult.None;
            crawlerbutton.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            crawlerbutton.DisabledFillColor = Color.Empty;
            crawlerbutton.DisabledForecolor = Color.Empty;
            crawlerbutton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            crawlerbutton.Font = new Font("Showcard Gothic", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            crawlerbutton.ForeColor = Color.White;
            crawlerbutton.IconLeft = (Image)resources.GetObject("crawlerbutton.IconLeft");
            crawlerbutton.IconLeftAlign = ContentAlignment.MiddleLeft;
            crawlerbutton.IconLeftCursor = Cursors.Default;
            crawlerbutton.IconLeftPadding = new Padding(11, 3, 3, 3);
            crawlerbutton.IconMarginLeft = 11;
            crawlerbutton.IconPadding = 10;
            crawlerbutton.IconRight = null;
            crawlerbutton.IconRightAlign = ContentAlignment.MiddleRight;
            crawlerbutton.IconRightCursor = Cursors.Default;
            crawlerbutton.IconRightPadding = new Padding(3, 3, 7, 3);
            crawlerbutton.IconSize = 25;
            crawlerbutton.IdleBorderColor = Color.Empty;
            crawlerbutton.IdleBorderRadius = 0;
            crawlerbutton.IdleBorderThickness = 0;
            crawlerbutton.IdleFillColor = Color.Empty;
            crawlerbutton.IdleIconLeftImage = (Image)resources.GetObject("crawlerbutton.IdleIconLeftImage");
            crawlerbutton.IdleIconRightImage = null;
            crawlerbutton.IndicateFocus = false;
            crawlerbutton.Location = new Point(-3, 384);
            crawlerbutton.Name = "crawlerbutton";
            crawlerbutton.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            crawlerbutton.OnDisabledState.BorderRadius = 1;
            crawlerbutton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            crawlerbutton.OnDisabledState.BorderThickness = 1;
            crawlerbutton.OnDisabledState.FillColor = Color.Transparent;
            crawlerbutton.OnDisabledState.ForeColor = Color.Transparent;
            crawlerbutton.OnDisabledState.IconLeftImage = null;
            crawlerbutton.OnDisabledState.IconRightImage = null;
            crawlerbutton.onHoverState.BorderColor = Color.Transparent;
            crawlerbutton.onHoverState.BorderRadius = 1;
            crawlerbutton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            crawlerbutton.onHoverState.BorderThickness = 1;
            crawlerbutton.onHoverState.FillColor = Color.Transparent;
            crawlerbutton.onHoverState.ForeColor = Color.White;
            crawlerbutton.onHoverState.IconLeftImage = null;
            crawlerbutton.onHoverState.IconRightImage = null;
            crawlerbutton.OnIdleState.BorderColor = Color.Transparent;
            crawlerbutton.OnIdleState.BorderRadius = 1;
            crawlerbutton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            crawlerbutton.OnIdleState.BorderThickness = 1;
            crawlerbutton.OnIdleState.FillColor = Color.Transparent;
            crawlerbutton.OnIdleState.ForeColor = Color.White;
            crawlerbutton.OnIdleState.IconLeftImage = (Image)resources.GetObject("crawlerbutton.OnIdleState.IconLeftImage");
            crawlerbutton.OnIdleState.IconRightImage = null;
            crawlerbutton.OnPressedState.BorderColor = Color.Transparent;
            crawlerbutton.OnPressedState.BorderRadius = 1;
            crawlerbutton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            crawlerbutton.OnPressedState.BorderThickness = 1;
            crawlerbutton.OnPressedState.FillColor = Color.Transparent;
            crawlerbutton.OnPressedState.ForeColor = Color.White;
            crawlerbutton.OnPressedState.IconLeftImage = null;
            crawlerbutton.OnPressedState.IconRightImage = null;
            crawlerbutton.Size = new Size(469, 112);
            crawlerbutton.TabIndex = 1;
            crawlerbutton.TextAlign = ContentAlignment.MiddleCenter;
            crawlerbutton.TextAlignment = HorizontalAlignment.Center;
            crawlerbutton.TextMarginLeft = 0;
            crawlerbutton.TextPadding = new Padding(0);
            crawlerbutton.UseDefaultRadiusAndThickness = true;
            // 
            // Dorkbutton
            // 
            Dorkbutton.AllowAnimations = true;
            Dorkbutton.AllowMouseEffects = true;
            Dorkbutton.AllowToggling = false;
            Dorkbutton.AnimationSpeed = 200;
            Dorkbutton.AutoGenerateColors = false;
            Dorkbutton.AutoRoundBorders = false;
            Dorkbutton.AutoSizeLeftIcon = true;
            Dorkbutton.AutoSizeRightIcon = true;
            Dorkbutton.BackColor = Color.Transparent;
            Dorkbutton.BackColor1 = Color.FromArgb(51, 122, 183);
            Dorkbutton.BackgroundImage = (Image)resources.GetObject("Dorkbutton.BackgroundImage");
            Dorkbutton.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Dorkbutton.ButtonText = "Dork Search";
            Dorkbutton.ButtonTextMarginLeft = 0;
            Dorkbutton.ColorContrastOnClick = 45;
            Dorkbutton.ColorContrastOnHover = 45;
            borderEdges7.BottomLeft = true;
            borderEdges7.BottomRight = true;
            borderEdges7.TopLeft = true;
            borderEdges7.TopRight = true;
            Dorkbutton.CustomizableEdges = borderEdges7;
            Dorkbutton.DialogResult = DialogResult.None;
            Dorkbutton.DisabledBorderColor = Color.FromArgb(191, 191, 191);
            Dorkbutton.DisabledFillColor = Color.Empty;
            Dorkbutton.DisabledForecolor = Color.Empty;
            Dorkbutton.FocusState = Bunifu.UI.WinForms.BunifuButton.BunifuButton.ButtonStates.Pressed;
            Dorkbutton.Font = new Font("Showcard Gothic", 12F, FontStyle.Bold, GraphicsUnit.Point, 0);
            Dorkbutton.ForeColor = Color.White;
            Dorkbutton.IconLeft = (Image)resources.GetObject("Dorkbutton.IconLeft");
            Dorkbutton.IconLeftAlign = ContentAlignment.MiddleLeft;
            Dorkbutton.IconLeftCursor = Cursors.Default;
            Dorkbutton.IconLeftPadding = new Padding(11, 3, 3, 3);
            Dorkbutton.IconMarginLeft = 11;
            Dorkbutton.IconPadding = 10;
            Dorkbutton.IconRight = null;
            Dorkbutton.IconRightAlign = ContentAlignment.MiddleRight;
            Dorkbutton.IconRightCursor = Cursors.Default;
            Dorkbutton.IconRightPadding = new Padding(3, 3, 7, 3);
            Dorkbutton.IconSize = 25;
            Dorkbutton.IdleBorderColor = Color.Empty;
            Dorkbutton.IdleBorderRadius = 0;
            Dorkbutton.IdleBorderThickness = 0;
            Dorkbutton.IdleFillColor = Color.Empty;
            Dorkbutton.IdleIconLeftImage = (Image)resources.GetObject("Dorkbutton.IdleIconLeftImage");
            Dorkbutton.IdleIconRightImage = null;
            Dorkbutton.IndicateFocus = false;
            Dorkbutton.Location = new Point(0, 249);
            Dorkbutton.Name = "Dorkbutton";
            Dorkbutton.OnDisabledState.BorderColor = Color.FromArgb(191, 191, 191);
            Dorkbutton.OnDisabledState.BorderRadius = 1;
            Dorkbutton.OnDisabledState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Dorkbutton.OnDisabledState.BorderThickness = 1;
            Dorkbutton.OnDisabledState.FillColor = Color.Transparent;
            Dorkbutton.OnDisabledState.ForeColor = Color.Transparent;
            Dorkbutton.OnDisabledState.IconLeftImage = null;
            Dorkbutton.OnDisabledState.IconRightImage = null;
            Dorkbutton.onHoverState.BorderColor = Color.Transparent;
            Dorkbutton.onHoverState.BorderRadius = 1;
            Dorkbutton.onHoverState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Dorkbutton.onHoverState.BorderThickness = 1;
            Dorkbutton.onHoverState.FillColor = Color.Transparent;
            Dorkbutton.onHoverState.ForeColor = Color.White;
            Dorkbutton.onHoverState.IconLeftImage = null;
            Dorkbutton.onHoverState.IconRightImage = null;
            Dorkbutton.OnIdleState.BorderColor = Color.Transparent;
            Dorkbutton.OnIdleState.BorderRadius = 1;
            Dorkbutton.OnIdleState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Dorkbutton.OnIdleState.BorderThickness = 1;
            Dorkbutton.OnIdleState.FillColor = Color.Transparent;
            Dorkbutton.OnIdleState.ForeColor = Color.White;
            Dorkbutton.OnIdleState.IconLeftImage = (Image)resources.GetObject("Dorkbutton.OnIdleState.IconLeftImage");
            Dorkbutton.OnIdleState.IconRightImage = null;
            Dorkbutton.OnPressedState.BorderColor = Color.Transparent;
            Dorkbutton.OnPressedState.BorderRadius = 1;
            Dorkbutton.OnPressedState.BorderStyle = Bunifu.UI.WinForms.BunifuButton.BunifuButton.BorderStyles.Solid;
            Dorkbutton.OnPressedState.BorderThickness = 1;
            Dorkbutton.OnPressedState.FillColor = Color.Transparent;
            Dorkbutton.OnPressedState.ForeColor = Color.White;
            Dorkbutton.OnPressedState.IconLeftImage = null;
            Dorkbutton.OnPressedState.IconRightImage = null;
            Dorkbutton.Size = new Size(469, 112);
            Dorkbutton.TabIndex = 0;
            Dorkbutton.TextAlign = ContentAlignment.MiddleCenter;
            Dorkbutton.TextAlignment = HorizontalAlignment.Center;
            Dorkbutton.TextMarginLeft = 0;
            Dorkbutton.TextPadding = new Padding(0);
            Dorkbutton.UseDefaultRadiusAndThickness = true;
            Dorkbutton.Click += Dorkbutton_Click;
            // 
            // guna2ControlBox1
            // 
            guna2ControlBox1.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            guna2ControlBox1.BackColor = Color.Transparent;
            guna2ControlBox1.BorderColor = Color.Transparent;
            guna2ControlBox1.ControlBoxType = Guna.UI2.WinForms.Enums.ControlBoxType.MaximizeBox;
            guna2ControlBox1.CustomizableEdges = customizableEdges1;
            guna2ControlBox1.FillColor = Color.Transparent;
            guna2ControlBox1.ForeColor = Color.Transparent;
            guna2ControlBox1.IconColor = Color.White;
            guna2ControlBox1.Location = new Point(2505, 0);
            guna2ControlBox1.Name = "guna2ControlBox1";
            guna2ControlBox1.ShadowDecoration.CustomizableEdges = customizableEdges2;
            guna2ControlBox1.Size = new Size(76, 49);
            guna2ControlBox1.TabIndex = 1;
            // 
            // guna2ControlBox2
            // 
            guna2ControlBox2.Anchor = AnchorStyles.Top | AnchorStyles.Right;
            guna2ControlBox2.BackColor = Color.Transparent;
            guna2ControlBox2.BorderColor = Color.Transparent;
            guna2ControlBox2.ControlBoxType = Guna.UI2.WinForms.Enums.ControlBoxType.MinimizeBox;
            guna2ControlBox2.CustomizableEdges = customizableEdges3;
            guna2ControlBox2.FillColor = Color.Transparent;
            guna2ControlBox2.ForeColor = Color.Transparent;
            guna2ControlBox2.IconColor = Color.White;
            guna2ControlBox2.Location = new Point(2430, 0);
            guna2ControlBox2.Name = "guna2ControlBox2";
            guna2ControlBox2.ShadowDecoration.CustomizableEdges = customizableEdges4;
            guna2ControlBox2.Size = new Size(76, 49);
            guna2ControlBox2.TabIndex = 2;
            // 
            // guna2ResizeForm1
            // 
            guna2ResizeForm1.TargetForm = this;
            // 
            // contentPanel
            // 
            contentPanel.AutoSizeMode = AutoSizeMode.GrowAndShrink;
            contentPanel.BackColor = Color.Transparent;
            contentPanel.Dock = DockStyle.Fill;
            contentPanel.Location = new Point(0, 0);
            contentPanel.Name = "contentPanel";
            contentPanel.Padding = new Padding(469, 0, 0, 0);
            contentPanel.Size = new Size(2583, 1381);
            contentPanel.TabIndex = 3;
            // 
            // Form1
            // 
            AutoScaleMode = AutoScaleMode.None;
            BackColor = Color.Black;
            BackgroundImage = (Image)resources.GetObject("$this.BackgroundImage");
            BackgroundImageLayout = ImageLayout.Stretch;
            ClientSize = new Size(2583, 1381);
            Controls.Add(guna2ControlBox2);
            Controls.Add(guna2ControlBox1);
            Controls.Add(bunifuGradientPanel1);
            Controls.Add(contentPanel);
            DoubleBuffered = true;
            FormBorderStyle = FormBorderStyle.None;
            Name = "Form1";
            RightToLeft = RightToLeft.No;
            StartPosition = FormStartPosition.CenterScreen;
            Text = "Form1";
            Load += Form1_Load_1;
            bunifuGradientPanel1.ResumeLayout(false);
            bunifuGradientPanel1.PerformLayout();
            ResumeLayout(false);
        }

        #endregion

        private Bunifu.UI.WinForms.BunifuGradientPanel bunifuGradientPanel1;
        private Bunifu.UI.WinForms.BunifuButton Dorkbutton;
        private Bunifu.UI.WinForms.BunifuButton dumperbutton;
        private Bunifu.UI.WinForms.BunifuButton Testerbutton;
        private Bunifu.UI.WinForms.BunifuButton crawlerbutton;
        private Bunifu.UI.WinForms.BunifuButton settingsbutton;
        private Bunifu.UI.WinForms.BunifuButton exitbutton;
        private Label label2;
        private Guna.UI2.WinForms.Guna2ControlBox guna2ControlBox1;
        private Guna.UI2.WinForms.Guna2ControlBox guna2ControlBox2;
        private Guna.UI2.WinForms.Guna2ResizeForm guna2ResizeForm1;
        private Bunifu.UI.WinForms.BunifuButton aboutbutton;
    }
}